# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dove < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/kickinranch/dove/"
  version "0.10.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kickinranch/dove/releases/download/v0.10.3/dove_0.10.3_darwin_amd64.tar.gz"
      sha256 "78dd962995eb7d220ad9542c83f94a8efbb39e69e6b3b923de4e53ca2b95678d"

      def install
        bin.install "dove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kickinranch/dove/releases/download/v0.10.3/dove_0.10.3_darwin_arm64.tar.gz"
      sha256 "8cc72ae2fc638d1906bd07be65aba0ed8a6ef561aecec4d6824728ced7c8eb5c"

      def install
        bin.install "dove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kickinranch/dove/releases/download/v0.10.3/dove_0.10.3_linux_arm64.tar.gz"
      sha256 "132d68639521d2a8daa997c5fc7b23ef0f48553ac48868e5745bcf373e5ca0b6"

      def install
        bin.install "dove"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kickinranch/dove/releases/download/v0.10.3/dove_0.10.3_linux_amd64.tar.gz"
      sha256 "3339eadffadbcc5c7d26f96bde9dba252f301ba4e04294b1c09a38ef26744df7"

      def install
        bin.install "dove"
      end
    end
  end
end
